### ISSUE TITLE
Missing capture logic

### ISSUE THREAD

**Issue by doc-han** [AmosAidoo/checkers#1]
In the position below white is to move. And as you can see the move marked with blue ink isn't permitted on the board. Needs to be fixed

![screenshot-amosaidoo com-2021 04 28-13_25_27](https://user-images.githubusercontent.com/35382021/116411658-71b6e500-a825-11eb-8733-899fc5510860.png)

**Comment by AmosAidoo** [comment]
This is an implementation of English checkers so its fine
